### ISSUE TITLE
fancy-garbling test failures

### ISSUE THREAD

**Issue by YANCC139** [GaloisInc/swanky#20]
When I run the fancy-carbling test without cargo test, the following error occurs：

failures:

---- parser::tests::test_gc_eval stdout ----
thread 'parser::tests::test_gc_eval' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', fancy-garbling/src/parser.rs:209:72
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- parser::tests::test_parser stdout ----
thread 'parser::tests::test_parser' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', fancy-garbling/src/parser.rs:180:68

---- twopac::semihonest::tests::test_aes stdout ----
thread 'twopac::semihonest::tests::test_aes' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', fancy-garbling/src/twopac/semihonest/mod.rs:110:68

**Comment by amaloz** [comment]
That's probably because it's not finding the correct file to load in. We're working on re-organizing the tests to use CARGO_MANIFEST_DIR as the base directory to hopefully avoid this situations in the future.
